function Hd = fir_equiripple_0_170(Fs)
%FIR_EQUIRIPPLE_0_170 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
% Generated on: 19-Dec-2018 09:47:10

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
% Fs Sampling Frequency

Fpass = 0;               % Passband Frequency
Fstop = 170;             % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.0001;          % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]